// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3SxqIjAFQUFs7uJjfF_gnnSeU8fKDovo',
    appId: '1:6563029265:web:c4c0664ef749c2ce9e2cb0',
    messagingSenderId: '6563029265',
    projectId: 'medicineapp-1eb89',
    authDomain: 'medicineapp-1eb89.firebaseapp.com',
    storageBucket: 'medicineapp-1eb89.appspot.com',
    measurementId: 'G-RD6DL3GEV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40Xh_3mQTFG-oJY8ZP1YRw-W1OHNP6H0',
    appId: '1:6563029265:android:f9b2edf2f93160a19e2cb0',
    messagingSenderId: '6563029265',
    projectId: 'medicineapp-1eb89',
    storageBucket: 'medicineapp-1eb89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb5jdYq8KOx2-AHS8e2YfI0huSpZfXDf0',
    appId: '1:6563029265:ios:a6f2fb1e067e796d9e2cb0',
    messagingSenderId: '6563029265',
    projectId: 'medicineapp-1eb89',
    storageBucket: 'medicineapp-1eb89.appspot.com',
    iosBundleId: 'com.example.aplikasiPertamaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb5jdYq8KOx2-AHS8e2YfI0huSpZfXDf0',
    appId: '1:6563029265:ios:a6f2fb1e067e796d9e2cb0',
    messagingSenderId: '6563029265',
    projectId: 'medicineapp-1eb89',
    storageBucket: 'medicineapp-1eb89.appspot.com',
    iosBundleId: 'com.example.aplikasiPertamaku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3SxqIjAFQUFs7uJjfF_gnnSeU8fKDovo',
    appId: '1:6563029265:web:6245c1a820e582cb9e2cb0',
    messagingSenderId: '6563029265',
    projectId: 'medicineapp-1eb89',
    authDomain: 'medicineapp-1eb89.firebaseapp.com',
    storageBucket: 'medicineapp-1eb89.appspot.com',
    measurementId: 'G-Z0V3ZD051Y',
  );

}